### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ctlllll** [FasterDecoding/Medusa#3]
# Roadmap

## Functionality
- [ ] Fine-tune Medusa heads together with LM head from scratch
- [ ] Distill from any model without access to the original training data
- [ ] Batched inference
- [ ] Fine-grained KV cache management

### Local Deployment
- [ ] [mlc-llm](https://github.com/mlc-ai/mlc-llm)
- [ ] [exllama](https://github.com/turboderp/exllama)
- [ ] [llama.cpp](https://github.com/ggerganov/llama.cpp)
### Serving
- [ ] [vllm](https://github.com/vllm-project/vllm)
- [ ] [TGI](https://github.com/huggingface/text-generation-inference)
- [ ] [lightllm](https://github.com/ModelTC/lightllm)

## Research
- [ ] Optimize the tree-based attention to reduce additional computation
- [ ] Improve the acceptance scheme to generate more diverse sequences

**Comment by JianbangZ** [comment]
Looks like a promising roadmap. I think llama.cpp support should be held a higher priority

**Comment by yhyu13** [comment]
Would Medusa compatible with GPTQ quantized models?

Specifically, two Medusa heads fine-tuned on unquantized and quantized model, would they be the same? Or can they be swapped？

**Comment by ctlllll** [comment]
> Would Medusa compatible with GPTQ quantized models?
> 
> Specifically, two Medusa heads fine-tuned on unquantized and quantized model, would they be the same? Or can they be swapped？

We didn't try this, but we can make an analogy to the 33B model we trained with `bitsandbytes`'s 8-bit quantized base model, where the difference seems to be minor. Yet, more investigation is needed :)

**Comment by AIApprentice101** [comment]
Please consider supporting quantized models, like GPTQ, AWQ, etc

**Comment by ctlllll** [comment]
> Please consider supporting quantized models, like GPTQ, AWQ, etc

Thanks for the suggestion. Those models should be easily integrated just by loading the base model in those formats. We are trying to integrate Medusa into frameworks that the speed actually benefits from quantization, e.g., mlc-llm, llama.cpp.

**Comment by ctlllll** [comment]
> > > Please consider supporting quantized models, like GPTQ, AWQ, etc
> > 
> > 
> > Thanks for the suggestion. Those models should be easily integrated just by loading the base model in those formats. We are trying to integrate Medusa into frameworks that the speed actually benefits from quantization, e.g., mlc-llm, llama.cpp.
> 
> Exciting. Is there a timeline for llama.cpp support? your best guess?

We'll start with MLC-LLM first as it's more user-friendly for integration. For llama.cpp, we currently don't have the bandwidth to do it and it would be greatly appreciated if there were volunteers who could help us with it :)

**Comment by ctlllll** [comment]
*🎉 Exciting News! 🎉*

We are thrilled to announce that we have received an award from [Chai Research](https://twitter.com/tianle_cai/status/1703891335147897341)! While the monetary value may not be substantial, we are dedicating it as a token of our appreciation for the invaluable contributions made by our community. The funds will be allocated as development bounties to incentivize the achievement of key milestones.

🏆 First Bounty: Porting Medusa to Llama.cpp #35  🏆
Bounty Amount: $100

**Comment by feifeibear** [comment]
Hello @ctlllll , Thanks for providing such a wonderful project. I am interested in the part of Fine-grained KV cache management. Could you offer me more guidance on this?

I have been working on a demo for SpeculativeSampling for a while.

https://github.com/feifeibear/LLMSpeculativeSampling

**Comment by ctlllll** [comment]
> Hello @ctlllll , Thanks for providing such a wonderful project. I am interested in the part of Fine-grained KV cache management. Could you offer me more guidance on this?
> 
> I have been working on a demo for SpeculativeSampling for a while.
> 
> https://github.com/feifeibear/LLMSpeculativeSampling
Hi @feifeibear , thanks for your interest! In the current version, we implemented a [pre-allocated KV cache](https://github.com/FasterDecoding/Medusa/blob/main/medusa/model/kv_cache.py) with the philosophy of keeping the original HF APIs and only for reducing the memory movement cost when updating KV cache. I think to be more dynamic, the PagedAttention mechanism in [vllm](https://github.com/vllm-project/vllm) might be a better reference :)

**Comment by nikshepsvn** [comment]
Hey all, any updates on this?

**Comment by ctlllll** [comment]
> Hey all, any updates on this?

We have some exciting stuff baking now. Let's wait and see :p

**Comment by nivibilla** [comment]
Hi, could sglang be placed on the roadmap too? It's a recent release also from lmsys who made vllm. But it's faster.

https://github.com/sgl-project/sglang
